# 학교폭력위험도 예측 모델 생성 
## 덕수고등학교 위치 변경(2022.01.06)
### 학교 이전: 성동구 왕십리로 199 → 송파구 위례북로 10

In [1]:
import pandas as pd
import numpy as np

data_path = "C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/3. Indicator_Data/"

# 환경지표

In [3]:
predict_enviroment = pd.read_csv(data_path + "DB_서울특별시_고등학교_학교폭력_지표.csv",index_col=0)
predict_enviroment

     시군구  환경지표_score  환경지표_cluster 환경지표_학교폭력위험도
0    강남구   19.071217             3         매우낮음
1    강동구   55.148267             2           보통
2    강북구  105.369939             1         매우높음
3    강서구   77.831186             1         매우높음
4    관악구   77.867433             4           높음
5    광진구   60.193732             2           보통
6    구로구   70.972259             4           높음
7    금천구   90.229114             1         매우높음
8    노원구   73.827367             2           보통
9    도봉구   89.946627             1         매우높음
10  동대문구   58.574818             2           보통
11   동작구   41.254694             2           보통
12   마포구   36.219280             3         매우낮음
13  서대문구   46.193799             2           보통
14   서초구   20.295262             3         매우낮음
15   성동구   38.346846             3         매우낮음
16   성북구   50.472787             2           보통
17   송파구   48.715229             3         매우낮음
18   양천구   65.103834             2           보통
19  영등포구   25.401159             3         매우낮음
20   용산구   38.593980             3         매우낮음
21   은평구   74.881966             2           보통
22   종로구   32.341505             0           낮음
23    중구   35.480837             0           낮음
24   중랑구   98.701102             1         매우높음

## 환경지표 -> 송파구

In [5]:
Deoksu_High_School = predict_enviroment.iloc[[17],:]
Deoksu_High_School

    시군구  환경지표_score  환경지표_cluster 환경지표_학교폭력위험도
17  송파구   48.715229             3         매우낮음

In [ ]:
# 위해지표